services:
  catalog:
    build:
      context: ./catalog
    command: [ "flask", "run", "--host=0.0.0.0"]
    ports:
      - 8081:5000
    expose:
      - 5000
  frontend:
    build:
      context: ./frontEnd
    command: [ "flask", "run", "--host=0.0.0.0"]
    ports:
      - 8080:5000
    expose:
      - 5000
  order:
    build:
      context: ./order
    command: [ "flask", "run", "--host=0.0.0.0"]
    ports:
      - 8082:5000
    expose:
      - 5000